package constant

const Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweEIwMDNjYUU3ZjgyZWVhZmEyN0JBZEUxNDlFRTZDNjRDN2QwQTBBNzMiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY4ODMwODg3MzIyMSwibmFtZSI6ImFpbmZ0In0.wkczxWemlih0jtK0syFujRmO_8NJJjuOt2X7s4sgXsM"
